services:
  python-api:
    image: mcr.microsoft.com/devcontainers/python:1-3.12-bookworm
    volumes:
      - ./backend:/workspace
    networks:
      - dev_net
    ports:
      - "5000:5000"
    entrypoint: ./.devcontainer/start.sh
    working_dir: /workspace

  node-app:
    image: mcr.microsoft.com/devcontainers/javascript-node:4-24-trixie
    volumes:
      - ./frontend:/workspace
    networks:
      - dev_net
    ports:
      - "4200:4200"
    entrypoint: ./.devcontainer/start.sh
    working_dir: /workspace

networks:
  dev_net:
    driver: bridge